name: Test backend verification

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  tests:
    name: nix-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: hax
        skipPush: true
        extraPullNames: fstar-nix-versions, z3-nix-versions

    - name: Install the toolchain
      run: |
        nix profile install nixpkgs#yq
        nix profile install .#rustc
        nix profile install .

    - name: Verify F* tests
      run: |
        nix develop .#ci-examples --command just test -b fstar -j 1

    - name: Verify Lean tests
      run: |
        nix develop .#ci-examples --command bash -c \
          "elan default \$(cat hax-lib/proof-libs/legacy-lean/lean-toolchain) && lake build --dir hax-lib/proof-libs/legacy-lean && just test -b legacy-lean"

    - name: Try to extract Rust By Examples
      run: |
        nix build .#rust-by-example-hax-extraction -L

  examples:
    name: example-${{ matrix.example }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - limited-order-book
          - chacha20
          - sha3
          - sha256
          - barrett
          - kyber_compress
          - loop_equivalence
          - proverif-psk
          - legacy_lean_chacha20
          - adc
    steps:
    - uses: actions/checkout@v4- uses: actions/checkout@v4    
    - name: Free disk space by removing preinstalled packages
      uses: jlumbroso/free-disk-space@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: hax
        skipPush: true
        extraPullNames: fstar-nix-versions, z3-nix-versions

    - name: Install the toolchain
      run: |
        nix profile install nixpkgs#yq
        nix profile install .#rustc
        nix profile install .

    - name: Install aeneas and charon
      run: ./install-aeneas.sh

    - name: Build the example
      run: |
        cd examples/${{ matrix.example }}
        PATH="$HOME/.cargo/bin:$PATH" nix develop ..#ci-examples --command make clean
        PATH="$HOME/.cargo/bin:$PATH" nix develop ..#ci-examples --command make